version: '3.8'

services:
  backend-app:
    build: ./backend  
    image: fantasy-backend:latest
    container_name: fantasy-backend
    ports:
      - '4000:4000'
    env_file:
    - ./backend/.env
    restart: on-failure
  frontend-app:
    build: ./frontend  
    image: fantasy-frontend:latest
    container_name: fantasy-frontend
    ports:
      - '3000:4173'
    depends_on:
      - backend-app 
    restart: on-failure